README.md, build_release.sh
This is a build script for Tax-Calculator, OG-USA, B-Tax conda packages, inclusive of uploading them to anaconda.org.
TODO:
=> first draft of build script for Tax-Calculator, OG-USA, B-Tax

build_release.sh
* Allow OSPC_PLATFORMS environment variable to control platforms for which packages are built
* Fix anaconda upload section
* Use `set -x` to get logging of commands
=> do not auto update conda-build - OSPC_PLATFORMS env var

build_release.sh
Allow OSPC_UPLOAD_TOKEN so this build_release.sh script can run remotely.
=> Ospc upload token

build_release.sh
Change version string for dev.
=> Fix dev channel

build_release.sh
Remove the --force argument to anaconda upload unless ANACONDA_FORCE=1 in env.
=> remove --force

build_release.sh
Avoid version conflict issue of 5/2/2017 with taxcalc 0.8.3
=> fixes to soften version pinning

build_release.sh
A return value was wrong in build_release.sh regarding anaconda upload.
=> fix build release return code regarding uploads

README.md, build_release.sh
=> Set default value for OSPC_PYTHONS

.gitignore, README-cli.md, policybrain_builder/cli/config.py, policybrain_builder/cli/main.py, policybrain_builder/cli/package.py, policybrain_builder/cli/repository.py, policybrain_builder/cli/utils.py, setup.py
This replaces the previous Bash script with a Python CLI. Skipping package builds and uploads is controlled by subcommands, instead of environment variables. See the new README for further information.
This PR partially addresses #45 and #49 and fixes #47, #48, and #51.
=> Add Python CLI

policybrain_builder/cli/main.py
=> Fix selection of Python version

policybrain_builder/cli/package.py
=> Use old build string for package names

policybrain_builder/cli/main.py, policybrain_builder/cli/package.py
=> Upload only selected Python versions

policybrain_builder/cli/repository.py, policybrain_builder/cli/utils.py
The ultimate cause of the failed validation check isn't certain but we no longer hide the error.
Related to #61
=> Fix silent error during validation of Git repo

policybrain_builder/cli/config.py, policybrain_builder/cli/main.py, policybrain_builder/cli/utils.py
=> Fix bug when cleaning working directory

README.md
This is just a documentation change to reflect one of changes in pull request #76.
=> Revise README.md to reflect change in PR #76

policybrain_builder/cli/main.py, setup.py
We've been using this successfully for long enough to upgrade the version number.
=> Update version from 0.0.1 to 0.1.0

.gitignore, gitpr, gitsync
Add development tools to policybrain-builder repo and revise contents of the `.gitignore` file.
=> Add gitsync and gitpr and update .gitignore file

builder.py
This PR aims to resolve the problems brought up in #82.
=> Clean up builder script

builder.py
Add warning that the `builder.py` script is still under development even though it has been merged into the master branch.
=> Revise builder.py docstring and fix pycodestyle error

policybrain_builder/cli/config.py, policybrain_builder/cli/main.py, setup.py
This pull request adds the ability to construct conda packages from code in the Behavioral-Responses repo.
=> Add behresp package

policybrain_builder/cli/main.py
Only logic change is to make the default value of the --label option be `main` instead of `dev`.
=> Streamline main.py code

policybrain_builder/cli/config.py, policybrain_builder/cli/main.py, policybrain_builder/cli/package.py, policybrain_builder/cli/repository.py, policybrain_builder/cli/utils.py, setup.py
This pull request eliminates almost all `pycodestyle` warnings, but there are no logic changes.
=> Streamlined code for pb version 0.4.0

policybrain_builder/cli/main.py
=> Standardize punctuation in help messages

policybrain_builder/cli/package.py, policybrain_builder/cli/repository.py
=> Modify progress statements

pb/cli/package.py
=> Fix line spacing in package.py

pb/cli/main.py, setup.py
=> Bump version to 0.8.0

pkgbld/__init__.py, pkgbld/release.py
Add virtually empty `pkgbld/release.py` file in which future development will take place.
=> Add pkgbld/release.py file

.gitignore, Makefile, conda.recipe/bld.bat, conda.recipe/build.sh, conda.recipe/install_local_package.sh, conda.recipe/meta.yaml, conda.recipe/remove_local_package.sh, environment.yml, pkgbld/tests/conftest.py, pkgbld/tests/test_4package.py
No change in basic logic; just adding `Makefile` and `environment.yml` and `conda.recipe/`  and `pkgbld/tests/` files.
=> Add tests and conda.recipe directories and related files

pkgbld/release.py
This pull request adds conda-convert logic to the release function in the `pkgbld/release.py` file.
=> Add convert logic to pkgbld/release.py file

RELEASES.md
No change in logic; just add a `RELEASES.md` file.
=> Add RELEASES.md file

RELEASES.md
This pull request fixes typo in the `RELEASES.md` file.  No change in logic.
=> Update RELEASES.md info

pkgbld/release.py, pkgbld/utils.py
Cosmetic code changes make nature of the version replacements clear in the top-level release.py code.
=> Refactor version-replacement code

RELEASES.md
Adds info to `RELEASES.md` about major changes contained in release 0.12.0
=> Update RELEASES.md info for release 0.12.0

RELEASES.md
=> Update RELEASES.md info on 0.12.1 version

README.md
=> Change location and color of badges

conda.recipe/meta.yaml
=> Remove test section of conda.recipe/meta.yaml

RELEASES.md, conda.recipe/meta.yaml
Reverts PSLmodels/Package-Builder#141
=> Revert "Restore test section of conda.recipe/meta.yaml file"

RELEASES.md, pkgbld/release.py
Revise the `anaconda upload` command by changing `--token` to `-t` and by changing `--user` to `-u`. Also, simplify code by using the `--skip-existing` option.
=> Revise 'anaconda upload' command in release.py

README.md, RELEASES.md, pkgbld/release.py
This pull request adds more debugging information about the final package upload logic.
=> Add 'anaconda upload' command print statement

README.md
=> Update README.md information for release 0.19.0

RELEASES.md
=> Fix typo in RELEASES.md file

pkgbld/release.py
=> Fix name of directory where build package is to be found for local install

README.md
Documentation enhancement based on @hdoupe's suggestions in the discussion of pull request #168.
=> Add extra channel documentation to README.md file
