- build_release.sh
@GoFroggyRun I'm going to just merge this, then you can pull from master.  I confirmed that I could replicate your bug and get past your bug with this PR.
Bug was related to usage of env variable $WORKSPACE which defined on Jenkins but not locally.
Also this PR sets the default anaconda label to `dev` to avoid inadvertent overwrite of existing packages.
> Fix default conda label

- build_release.sh
IFS is a built in bash env var that determines how bash splits strings.  I changed IFS in the script at one point, but failed to unset it back to what it was.  Hopefully this is what we need for the bug reported by @GoFroggyRun of the python versions being mashed together - "2.7 3.4 3.5 3.6" instead of just one of those.
> fix string splitting bash env var IFS - unset it

- build_release.sh
In PR #27 - the env variable $version was inadvertently being set twice (the second time unexpected).
> fix env vars typo regarding dev versions

- build_release.sh
`build_release.sh` was not detecting the highest version number.
> fix detection of highest version number

- policybrain_builder/cli/main.py
- policybrain_builder/cli/utils.py
This isn't on by default. I added the flag to make this behavior explicit and also to alleviate the need to manually remove the directory prior to building.
Related to #61
> Add flag to clean working directory between builds

- policybrain_builder/cli/config.py
- policybrain_builder/cli/package.py
This pull request removes the **linux-32** platform from the PLATFORMS list, which is hard-wired and cannot be changed using a command-line option.  No linux-32 `taxcalc` packages have been downloaded over the past year; no linux-32 `ogusa` packages have been downloaded over the past 26 months; and no linux-32 `btax` packages have been downloaded over the whole history of that project.
This pull request also removes the '3.5' item in the PYTHON_VERSIONS list because for many months now we have not been supporting Python 3.5 and we have no plans of doing that.  This change will improve the usability of the `pb` tool because this change will eliminate the need to two command-line options.
This pull request does not change any logic; it just shortens two lists.
> Revise PLATFORMS list and PYTHON_VERSIONS list

- builder.py
This PR proposes a simple script that does most of the things that this repo does but in a simpler way.
Advantages:
- Can build and upload conda packages for any repo that has the required `meta.yaml`, `bld.bat`, and `bld.sh` files. The current setup works only for a couple packages and is very restrictive in how those are setup.
- Very simple--it is about 70 lines long and it is pretty straightforward to grok what is going on and make changes
Disadvantages:
- I haven't added any commandline argument parses to this beyond reading items from `sys.argv`. A basic argument parser can be added with little effort using `argparse` or something similar.
- This repo is polished and has very nice ouptut. This script dumps all output to stdout without the fancy colors.
- There may be a few other …
> Add simple script for releasing packages

- README.md
- builder.py
This pull request provides documentation for usage of the `pb` CLI tool in releasing conda `taxcalc` packages for Python 3.6 only.
> Update README.md with link to new taxcalc usage example

- policybrain_builder/cli/config.py
- policybrain_builder/cli/main.py
- policybrain_builder/cli/package.py
- policybrain_builder/cli/utils.py
- setup.py
This pull request makes a couple of changes in the code to handle the new warning messages emitted from recent versions of conda-build.  Now calls to conda build often return these new lines of output:
```
read filter "zstd" is not supported
write filter "zstd" is not supported
```
Another substantive change is that now only packages for Python 3.6 can be generated (that is, no Python 2.7 packages are generated).
In addition, the code in `packages.py` has been reformatted so that `pycodestyle` generates fewer errors when run over all the `*py` files in the repository.
> Changes for version 0.3.0

- .gitignore
- policybrain_builder/cli/main.py
- release-packages.sh
- setup.py
The new `release-packages.sh` bash script uses version 0.6.0 of the `pb` CLI tool to build, and upload to the Anaconda Cloud, conda packages for Tax-Calculator and for other models in the USA tax collection of the Policy Simulation Library (PSL).   It works smoothly for Tax-Calculator (taxcalc) and for Behavioral-Responses (behresp), and it will be tested soon on other models in the PSL USA tax collection.  After that additional testing, the documentation for this repo will be revised to reflect the current version of `pb` and `release-packages.sh`.
> Add release-packages.sh script to repository

- pkgbld/release.py
This pull request adds a clean-up command (`conda build purge`) and a `try ... except` statement to catch any `OSError` generated by the `anaconda upload` command, which is most likely being generated by the fact that the package that is being uploaded already exists in the Anaconda Cloud.  This approach is taken from the earlier version authored by @jbcrail.
> Don't stop on 'anaconda upload' errors; add 'conda build purge'

- conda.recipe/meta.yaml
- pkgbld/__init__.py
- pkgbld/cli.py
- pkgbld/release.py
This pull request adds to the Package-Builder `pkgbld` package a CLI to the release function.  This means that when the `pkgbld` package is installed, it is possible to build and upload to the Anaconda Cloud conda packages for any release of a Policy Simulation Library (PSL) model that follows the PSL conda-building criteria.  This can be accomplished as the operating-system command prompt as in the following example:
```
$ conda install -c PSLmodels pkgbld --yes
$ pbrelease B-Tax btax 0.2.5
```
The second command produces an enormous amount of output to the screen because it invokes several `conda` and `anaconda` utilities that produce enormous amount of output that are a mixture of writes to stdout (1) and writes to stderr (2).  If you're working on a Mac, you can filter out all the …
> Add pbrelease CLI to release function

- pkgbld/cli.py
- pkgbld/release.py
This pull request adds command-line argument checking logic to the `cli.py` file so that error messages are easier to understand for users of the `pbrelease` command-line interface to Package-Builder.  
There are no changes to the basic logic of Package-Builder.
> Add argument checking and simpler error messages to cli.py

- pkgbld/cli.py
This pull request adds an easier to understand error message to the `pbrelease` CLI to Package-Builder.
> Add CLI check for existence of Anaconda token file

- pkgbld/release.py
This pull request implements a significant speed-up in Package-Builder by avoiding the download of the whole repository and then doing a checkout of the specified version.  The speed-up is implemented by using "git clone" options that download only the code for the specified version.  No change in the basic logic of the Package-Builder.
> Make 'git clone' faster by downloading only code for version (not the whole repository)

- README.md
- pkgbld/release.py
This pull request adds `README.md` documentation about how to use the new Package-Builder `pbrelease` command-line tool.
> Initial version of new README.md documentation

- pkgbld/cli.py
- pkgbld/release.py
- pkgbld/tests/test_release.py
This pull request adds to the `pbrelease` tool two new options:  `--also37`, which builds/uploads packages for Python 3.7 as well as Python 3.6, and `--dryrun`, which shows the build/upload plan and quits without executing the plan.
> Add --also37 and --dryrun options

- RELEASES.md
- conda.recipe/meta.yaml
- environment.yml
- setup.py
This pull request makes changes necessary for building/uploading `pkgbld` packages for Python 3.7 as well as for Python 3.6.
> Changes for release 0.12.2

- RELEASES.md
- conda.recipe/meta.yaml
- environment.yml
The need for this revision has been pointed out by the testing of release 0.13.0 on a Linux/Python37 platform by @hdoupe.    The following instructions (found high in the results of a Google search) also suggest the need for this revision.
> Add anaconda-client as a required dependency

- README.md
- RELEASES.md
- conda.recipe/meta.yaml
- environment.yml
- pkgbld/release.py
The anaconda-client versions 1.7.? are just tagged; they are not labeled as releases.
> Force upload of already uploaded packages; use anaconda-client=1.6

- RELEASES.md
- pkgbld/release.py
Cosmetic changes that show when the build/upload was done and how long it took.
> Add datetime to both the :starting and :finishing prints

- README.md
This pull request adds documentation about how to get a token file, which is required for the use of the `pbrelease` tool.  The need for this documentation was pointed out by @andersonfrailey in issue #155.
Thanks, @andersonfrailey, for pointing out the need for this documentation enhancement.
> Update README about getting PSLmodels token file

- README.md
- RELEASES.md
- pkgbld/cli.py
- pkgbld/release.py
This pull request simplifies the `--local` command-line option and revises the local logic so the the locally-installed package has the version specified on the command line (rather than always being 0.0.0).
> Simplify --local option and generalize its version logic
